version: '2'

services:
  alfresco-core:
    image: ${DOCKER_IMAGE}
    ports:
    - ${DOCKER_IP}::8080
    volumes:
    - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
    - SOLR_HOST=solr
    - TERM=xterm
    ## Needed for Solr indexing
    - GLOBAL_local.transform.service.enabled=true
    # Disable transformations and renditions
    - GLOBAL_contentPropertyRestrictions.enabled=false
    - GLOBAL_ooo.enabled=false
    - GLOBAL_jodconverter.enabled=false
    - GLOBAL_transform.service.enabled=false
    - GLOBAL_legacy.transform.service.enabled=false

  solr:
    image: private.docker.xenit.eu/alfresco-enterprise/alfresco-solr6:2.0.3
    restart: unless-stopped
    environment:
    - ALFRESCO_HOST=alfresco-core

  postgresql:
    image: docker.io/xenit/postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    restart: unless-stopped

#  jodconverter:
#    image: hub.xenit.eu/public/jodconverter-ws
#    restart: unless-stopped

volumes:
  alfresco:
  solr:
  postgres: