services:
  alfresco-core:
    image: ${DOCKER_IMAGE:-image_not_set}
    ports:
      - "${DOCKER_IP}:8080:8080"
      - "4578:4578" # coderunner-server
    volumes:
      - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
      - TERM=xterm
      - TOMCAT_ALLOW_CASUAL_MULTIPART_PARSING=false
      - GLOBAL_messaging.broker.url=failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true
      - GLOBAL_localTransform.core-aio.url=http://transform-core-aio:8090/
      - GLOBAL_sfs.url=http://shared-file-store:8099/
      - GLOBAL_index.subsystem.name=elasticsearch
      - GLOBAL_elasticsearch.host=elasticsearch
      - GLOBAL_elasticsearch.createIndexIfNotExists=true
      - GLOBAL_elasticsearch.index.locale=en
      - GLOBAL_file.encoding=utf-8
      #- GLOBAL_elasticsearch.port=9200

  elasticsearch:
    image: elasticsearch:7.17.28
    environment:
      - discovery.type=single-node
      #- xpack.security.enabled=true
      #- ELASTIC_PASSWORD=alfresco
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

#  elasticsearch-live-indexing:
#    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing
#    environment:
#      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
#      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
#      ALFRESCO_SHAREDFILESTORE_BASEURL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/

  postgresql:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco
    restart: unless-stopped

  activemq:
    image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
    mem_limit: 1g

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.1.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"

  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:3.0.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000

volumes:
  alfresco:
  elasticsearch:
  postgres:
