version: '2'
services:
  alfresco-core:
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - SHARE_HOST=alfresco-share
      - LOG4J_logger.eu.xenit.apix.util.SolrTestHelper=DEBUG
  alfresco-share:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-share-enterprise:5.2
    ports:
      - 8090:8080
    environment:
      - DEBUG=true
      - ALFRESCO_HOST=alfresco-core
      - ALFRESCO_INTERNAL_HOST=alfresco-core
