version: '2'
services:
  alfresco-core:
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - SHARE_HOST=localhost
      - ALFRESCO_HOST=localhost
#      - SHARE_HOST=alfresco-core
  alfresco-share:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-share-enterprise:5.2
    ports:
      - 8090:8080
    environment:
      - DEBUG=true
      - ALFRESCO_HOST=alfresco-core
