version: '2'

services:
  alfresco-core:
    image: ${DOCKER_IMAGE}
    ports:
    - ${DOCKER_IP}::8080
    volumes:
    - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
    - SOLR_HOST=solr

  solr:
    image: hub.xenit.eu/alfresco-solr6:1.1.1
    restart: unless-stopped
    environment:
    - ALFRESCO_HOST=alfresco-core

  postgresql:
    image: docker.io/xeniteu/postgres:10.10
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    restart: unless-stopped

  jodconverter:
    image: hub.xenit.eu/public/jodconverter-ws
    restart: unless-stopped

volumes:
  alfresco:
  solr:
  postgres: