version: '2'
services:
  alfresco-core:
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - SHARE_HOST=alfresco-share
      # overload of jcl by spring 5, causes classloader conflict. Avoiding by declaring default logfactoryimpl.
      # See http://commons.apache.org/proper/commons-logging/troubleshooting.html ,section `The Incompatible LogFactory Issue` for more info.
      - JAVA_OPTS_designateLogFactoryImpl="-Dorg.apache.commons.logging.LogFactory=org.apache.commons.logging.impl.LogFactoryImpl"
  alfresco-share:
    image: hub.xenit.eu/public/alfresco-share-community:7.0.0
    ports:
      - 8090:8080
    environment:
      - DEBUG=true
      - ALFRESCO_HOST=alfresco-core
