version: '2'

services:
  alfresco-core:
    image: ${DOCKER_IMAGE}
    ports:
      - "${DOCKER_IP}::8080"
    volumes:
      - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
      - SOLR_HOST=solr
      - TERM=xterm
      - GLOBAL_transform.service.enabled=false
      - GLOBAL_local.transform.service.enabled=false
      - GLOBAL_legacy.transform.service.enabled=false
      - GLOBAL_messaging.broker.url=failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true

  solr:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-solr6:2.0.1
    volumes:
      - solr:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
      - ALFRESCO_HOST=alfresco-core

  postgresql:
    image: docker.io/xenit/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco
    restart: unless-stopped

  activemq:
    image: alfresco/alfresco-activemq:5.16.1
    mem_limit: 1g
#    ports:
#      - "8161:8161" # Web Console
#      - 5672:5672 # AMQP
#      - 61616:61616 # OpenWire
#      - 61613:61613


volumes:
  alfresco:
  solr:
  postgres:
