version: '2'

services:
  alfresco-core:
    image: ${DOCKER_IMAGE}
    ports:
      - "${DOCKER_IP}::8080"
    volumes:
      - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
      - SOLR_HOST=solr
      - TERM=xterm
      - GLOBAL_messaging.broker.url=failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true
      - GLOBAL_localTransform.core-aio.url=http://transform-core-aio:8090/
      - Transformers.autoStart=true

  solr:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-solr6:2.0.1
    volumes:
      - solr:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
      - ALFRESCO_HOST=alfresco-core

  postgresql:
    image: docker.io/xenit/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco
    restart: unless-stopped

  activemq:
    image: alfresco/alfresco-activemq:5.16.1
    mem_limit: 1g

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.5.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"

volumes:
  alfresco:
  solr:
  postgres:
