package eu.xenit.alfred.api;
/*
* WARNING: THIS FILE IS AUTO-GENERATED BY GRADLE DURING BUILD. 
* ANY CHANGES TO THIS FILE WILL BE LOST AFTER NEW BUILD.
* SEE Gradle task generateVersionFile
*/
public class Version {
public static final String Number = "6.1.1";
}
