name: 'Continuous Integration'
on:
  push:
  workflow_dispatch:
env:
  ALFRESCO_NEXUS_USERNAME: ${{ secrets.ALFRESCO_NEXUS_USERNAME }}
  ALFRESCO_NEXUS_PASSWORD: ${{ secrets.ALFRESCO_NEXUS_PASSWORD }}
  SIGNING_PRIVATE_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
  SIGNING_PASSWORD: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
  ORG_GRADLE_PROJECT_mavenCentralPublishUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPublishPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  BRANCH_NAME: ${{ github.ref_name }}
jobs:
  alfred-api-interface:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Login to Xenit Harbor
        uses: docker/login-action@v3
        with:
          registry: docker.xenit.eu
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build interface  # Execute before integration testing to catch errors early
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: :alfred-api-interface:build :alfred-api-interface:javadoc
      - name: Unit test REST API
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: --info :alfred-api-rest:test
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: :alfred-api-interface:publish

  alfred-api-impl:
    strategy:
      matrix:
        alfresco_version: [ 231, 232, 233, 234, 251 ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Login to Xenit Harbor
        uses: docker/login-action@v3
        with:
          registry: docker.xenit.eu
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build and test
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: >-
            --info
            :alfred-api-impl:alfred-api-impl-${{ matrix.alfresco_version }}:test
            :alfred-api-integrationtests-client:alfresco:${{ matrix.alfresco_version }}:integrationTest
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.6
        if: success() || failure()
        with:
          check_name: "test-reports-${{ matrix.alfresco_version }}"
          report_paths: '**/build/test-results/**/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detailed_summary: true
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: :alfresco:${{ matrix.alfresco_version }}:publish
